# Setup XDG Portals
exec-once = source $HOME/.config/hypr/scripts/xdg.sh

# Load waybar
exec-once = waybar

# Start Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Load wallpaper
exec-once = hyprpaper

# Load notification daemon
exec-once = swaync

# Load GTK Settings
exec-once = source $HOME/.config/hypr/scripts/gtk.sh

# Load idle daemon
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Load hyprshade
exec-once = hyprshade auto
